// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProfile() {
  return window['go']['profile']['Profile']['GetProfile']();
}

export function SaveProfile() {
  return window['go']['profile']['Profile']['SaveProfile']();
}
